version: "3.9"

services:
  backend-app:
    build: .
    container_name: backend-app
    restart: unless-stopped
environment:
	DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_test_db
    expose:
      - "8000"
networks:
  web:
    external: true
  internal:
    external: true
